name: meiqiachat
description: fork 来的，不断修改
version: 1.1.3
author: stormxx <stormxx@gmail.com>
homepage: 'https://github.com/Stormxx/meiqiachat'
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.kefu.ding.meiqiachat
    pluginClass: MeiqiachatPlugin
